#!/bin/sh
#
### BEGIN INIT INFO
# Provides: weston
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

export XDG_RUNTIME_DIR=/run/user/root

WS_CALUDEV_FILE=/etc/udev/rules.d/20-touch.rules

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

case "$1" in
  start)

        # If there's no touchscreen device available, done
        if [ ! -e /dev/input/touchscreen0 ] ; then
            exit 0
        fi

        # If it was already calibrated, done
        if [ -f "$WS_CALUDEV_FILE" ] ; then
            exit 0
        fi

        # Run a calibration app and save output to udev rules
        echo    "Calibrating touchscreen (first time only)"
        echo
        echo    "*** To continue, please complete the touchscreen calibration"
        echo -n "*** by touching the crosshairs on the LCD screen"
        CAL_VALUES=`weston-calibrator|cut -c21-`
        echo 'SUBSYSTEM=="input", ENV{WL_CALIBRATION}="'$CAL_VALUES'"' > $WS_CALUDEV_FILE
        echo "."

        # Reload and re-run udev rules and restart weston
        udevadm control --reload
        udevadm trigger
        killproc weston
        sleep 1

        weston-start -- $OPTARGS

  ;;

  *)
        echo "usage: $0 { start }"
  ;;
esac

exit 0
